CREATE TABLE IF NOT EXISTS site_home_services (id INT AUTO_INCREMENT PRIMARY KEY, serviceId VARCHAR(100) NOT NULL UNIQUE, path VARCHAR(255) NOT NULL, titleAr TEXT NOT NULL, titleEn TEXT NOT NULL, subAr TEXT NOT NULL, subEn TEXT NOT NULL, descAr TEXT NOT NULL, descEn TEXT NOT NULL, badgeAr TEXT NULL, badgeEn TEXT NULL, externalUrl TEXT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_about_certifications (id INT AUTO_INCREMENT PRIMARY KEY, value TEXT NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_about_stats (id INT AUTO_INCREMENT PRIMARY KEY, value TEXT NOT NULL, labelAr TEXT NOT NULL, labelEn TEXT NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_about_courses (id INT AUTO_INCREMENT PRIMARY KEY, labelAr TEXT NOT NULL, labelEn TEXT NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_about_contacts (id INT AUTO_INCREMENT PRIMARY KEY, labelAr TEXT NOT NULL, labelEn TEXT NOT NULL, valueAr TEXT NULL, valueEn TEXT NULL, value TEXT NULL, hrefType VARCHAR(30) NULL, href TEXT NULL, color VARCHAR(100) NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_resource_decisions (id INT AUTO_INCREMENT PRIMARY KEY, year VARCHAR(10) NOT NULL, title TEXT NOT NULL, badge TEXT NOT NULL, description TEXT NOT NULL, date TEXT NOT NULL, href TEXT NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_resource_links (id INT AUTO_INCREMENT PRIMARY KEY, label TEXT NOT NULL, description TEXT NOT NULL, href TEXT NOT NULL, color VARCHAR(100) NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_resource_questions (id INT AUTO_INCREMENT PRIMARY KEY, question TEXT NOT NULL, yes TEXT NOT NULL, no TEXT NOT NULL, risk VARCHAR(20) NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_faq_categories (id INT AUTO_INCREMENT PRIMARY KEY, category TEXT NOT NULL, icon VARCHAR(20) NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS site_faq_questions (id INT AUTO_INCREMENT PRIMARY KEY, categoryId INT NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, sortOrder INT NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Idempotent backfill: only populate an empty normalized table. Legacy values
-- remain untouched and can be re-read if a partial backfill is encountered.
INSERT INTO site_home_services (serviceId,path,titleAr,titleEn,subAr,subEn,descAr,descEn,badgeAr,badgeEn,externalUrl,sortOrder)
SELECT j.serviceId,j.path,j.titleAr,j.titleEn,j.subAr,j.subEn,j.descAr,j.descEn,j.badgeAr,j.badgeEn,j.externalUrl,j.ord - 1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (ord FOR ORDINALITY, serviceId VARCHAR(100) PATH '$.id', path VARCHAR(255) PATH '$.path', titleAr TEXT PATH '$.titleAr', titleEn TEXT PATH '$.titleEn', subAr TEXT PATH '$.subAr', subEn TEXT PATH '$.subEn', descAr TEXT PATH '$.descAr', descEn TEXT PATH '$.descEn', badgeAr TEXT PATH '$.badgeAr' NULL ON EMPTY, badgeEn TEXT PATH '$.badgeEn' NULL ON EMPTY, externalUrl TEXT PATH '$.externalUrl' NULL ON EMPTY)) j WHERE s.`key`='homeServices' AND NOT EXISTS (SELECT 1 FROM site_home_services);
INSERT INTO site_about_certifications (value,sortOrder) SELECT j.value,j.ord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (ord FOR ORDINALITY, value TEXT PATH '$')) j WHERE s.`key`='aboutCertifications' AND NOT EXISTS (SELECT 1 FROM site_about_certifications);
INSERT INTO site_about_stats (value,labelAr,labelEn,sortOrder) SELECT j.value,j.labelAr,j.labelEn,j.ord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (ord FOR ORDINALITY,value TEXT PATH '$.value',labelAr TEXT PATH '$.labelAr',labelEn TEXT PATH '$.labelEn')) j WHERE s.`key`='aboutStats' AND NOT EXISTS (SELECT 1 FROM site_about_stats);
INSERT INTO site_about_courses (labelAr,labelEn,sortOrder) SELECT j.labelAr,j.labelEn,j.ord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (ord FOR ORDINALITY,labelAr TEXT PATH '$.labelAr',labelEn TEXT PATH '$.labelEn')) j WHERE s.`key`='aboutCourses' AND NOT EXISTS (SELECT 1 FROM site_about_courses);
INSERT INTO site_about_contacts (labelAr,labelEn,valueAr,valueEn,value,hrefType,href,color,sortOrder) SELECT j.labelAr,j.labelEn,j.valueAr,j.valueEn,j.value,j.hrefType,j.href,j.color,j.ord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (ord FOR ORDINALITY,labelAr TEXT PATH '$.labelAr',labelEn TEXT PATH '$.labelEn',valueAr TEXT PATH '$.valueAr' NULL ON EMPTY,valueEn TEXT PATH '$.valueEn' NULL ON EMPTY,value TEXT PATH '$.value' NULL ON EMPTY,hrefType VARCHAR(30) PATH '$.hrefType' NULL ON EMPTY,href TEXT PATH '$.href' NULL ON EMPTY,color VARCHAR(100) PATH '$.color')) j WHERE s.`key`='aboutContacts' AND NOT EXISTS (SELECT 1 FROM site_about_contacts);
INSERT INTO site_resource_decisions (year,title,badge,description,date,href,sortOrder) SELECT s2.year,j.title,j.badge,j.description,j.date,j.href,j.ord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$.*' COLUMNS (year VARCHAR(10) PATH '$.key', items JSON PATH '$.value')) s2 JOIN JSON_TABLE(s2.items, '$[*]' COLUMNS (ord FOR ORDINALITY,title TEXT PATH '$.title',badge TEXT PATH '$.badge',description TEXT PATH '$.desc',date TEXT PATH '$.date',href TEXT PATH '$.href')) j WHERE s.`key`='resourcesDecisions' AND NOT EXISTS (SELECT 1 FROM site_resource_decisions);
INSERT INTO site_resource_links (label,description,href,color,sortOrder) SELECT j.label,j.description,j.href,j.color,j.ord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (ord FOR ORDINALITY,label TEXT PATH '$.label',description TEXT PATH '$.desc',href TEXT PATH '$.href',color VARCHAR(100) PATH '$.color')) j WHERE s.`key`='resourcesOfficialLinks' AND NOT EXISTS (SELECT 1 FROM site_resource_links);
INSERT INTO site_resource_questions (question,yes,no,risk,sortOrder) SELECT j.question,j.yes,j.no,j.risk,j.ord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (ord FOR ORDINALITY,question TEXT PATH '$.question',yes TEXT PATH '$.yes',no TEXT PATH '$.no',risk VARCHAR(20) PATH '$.risk')) j WHERE s.`key`='resourcesComplianceQuestions' AND NOT EXISTS (SELECT 1 FROM site_resource_questions);
INSERT INTO site_faq_categories (category,icon,sortOrder) SELECT j.category,j.icon,j.ord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (ord FOR ORDINALITY,category TEXT PATH '$.category',icon VARCHAR(20) PATH '$.icon')) j WHERE s.`key`='faqCategories' AND NOT EXISTS (SELECT 1 FROM site_faq_categories);
INSERT INTO site_faq_questions (categoryId,question,answer,sortOrder) SELECT c.id,q.question,q.answer,q.qord-1 FROM site_content s JOIN JSON_TABLE(s.`value`, '$[*]' COLUMNS (cord FOR ORDINALITY,category TEXT PATH '$.category',questions JSON PATH '$.questions')) j JOIN site_faq_categories c ON c.category=j.category JOIN JSON_TABLE(j.questions, '$[*]' COLUMNS (qord FOR ORDINALITY,question TEXT PATH '$.q',answer TEXT PATH '$.a')) q WHERE s.`key`='faqCategories' AND NOT EXISTS (SELECT 1 FROM site_faq_questions);
