import type { MySql2Database } from "drizzle-orm/mysql2";
import { inArray } from "drizzle-orm";
import { hcKpiCategories, hcBuiltinIndicators, translations } from "../../drizzle/schema";
const HC_CATEGORIES = [
  { key: "saudization",  ar: "التوطين والتنوع",        en: "Saudization & Diversity",    color: "oklch(0.55 0.18 145)" },
  { key: "retention",    ar: "الاستقطاب والاحتفاظ",    en: "Recruitment & Retention",    color: "oklch(0.55 0.22 220)" },
  { key: "training",     ar: "التطوير والتدريب",        en: "Development & Training",     color: "oklch(0.55 0.22 290)" },
  { key: "productivity", ar: "الإنتاجية والأداء",       en: "Productivity & Performance", color: "oklch(0.62 0.20 55)"  },
  { key: "cost",         ar: "التكاليف والكفاءة",       en: "Cost & Efficiency",          color: "oklch(0.58 0.22 25)"  },
  { key: "governance",   ar: "الحوكمة المؤسسية",        en: "Corporate Governance",       color: "oklch(0.55 0.22 195)" },
];

const BUILTIN_INDICATORS = [
  // ── التوطين والتنوع ──────────────────────────────────────────────────────────
  {
    key: "saudization_rate",
    nameAr: "نسبة السعودة الفعلية",
    nameEn: "Saudization Rate",
    category: "saudization",
    categoryAr: "التوطين والتنوع",
    categoryEn: "Saudization & Diversity",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "حسب نطاق المنشأة (نطاقات وزارة الموارد البشرية)",
    benchmarkEn: "Per Nitaqat band (HRSD)",
    descriptionAr: "نسبة العمالة السعودية من إجمالي العمالة",
    descriptionEn: "Percentage of Saudi employees out of total workforce",
    higherIsBetter: true,
  },
  {
    key: "saudi_leadership_rate",
    nameAr: "نسبة القيادات السعودية",
    nameEn: "Saudi Leadership Rate",
    category: "saudization",
    categoryAr: "التوطين والتنوع",
    categoryEn: "Saudization & Diversity",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "30% كحد أدنى في المناصب القيادية",
    benchmarkEn: "30% minimum in leadership roles",
    descriptionAr: "نسبة السعوديين في المناصب القيادية والإشرافية",
    descriptionEn: "Percentage of Saudis in leadership and supervisory roles",
    higherIsBetter: true,
  },
  {
    key: "women_workforce_rate",
    nameAr: "نسبة المرأة في القوى العاملة",
    nameEn: "Women Workforce Rate",
    category: "saudization",
    categoryAr: "التوطين والتنوع",
    categoryEn: "Saudization & Diversity",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "30% وفق رؤية 2030",
    benchmarkEn: "30% per Vision 2030 target",
    descriptionAr: "نسبة النساء من إجمالي القوى العاملة",
    descriptionEn: "Percentage of women in total workforce",
    higherIsBetter: true,
  },
  {
    key: "persons_with_disabilities_rate",
    nameAr: "نسبة توظيف ذوي الإعاقة",
    nameEn: "Persons with Disabilities Rate",
    category: "saudization",
    categoryAr: "التوطين والتنوع",
    categoryEn: "Saudization & Diversity",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "1% من إجمالي القوى العاملة (نظام العمل)",
    benchmarkEn: "1% of total workforce (Labor Law)",
    descriptionAr: "نسبة توظيف ذوي الإعاقة من إجمالي الموظفين",
    descriptionEn: "Employment rate of persons with disabilities",
    higherIsBetter: true,
  },

  // ── الاستقطاب والاحتفاظ ──────────────────────────────────────────────────────
  {
    key: "turnover_rate",
    nameAr: "معدل دوران الموظفين",
    nameEn: "Employee Turnover Rate",
    category: "retention",
    categoryAr: "الاستقطاب والاحتفاظ",
    categoryEn: "Recruitment & Retention",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "أقل من 15% سنوياً (معيار دولي)",
    benchmarkEn: "Below 15% annually (global benchmark)",
    descriptionAr: "نسبة الموظفين الذين تركوا المنظمة خلال الفترة",
    descriptionEn: "Percentage of employees who left during the period",
    higherIsBetter: false,
  },
  {
    key: "avg_tenure",
    nameAr: "متوسط مدة الخدمة",
    nameEn: "Average Employee Tenure",
    category: "retention",
    categoryAr: "الاستقطاب والاحتفاظ",
    categoryEn: "Recruitment & Retention",
    unit: "سنة",
    unitAr: "سنة",
    benchmarkAr: "3-5 سنوات (متوسط القطاع)",
    benchmarkEn: "3-5 years (sector average)",
    descriptionAr: "متوسط عدد سنوات خدمة الموظفين في المنظمة",
    descriptionEn: "Average number of years employees stay in the organization",
    higherIsBetter: true,
  },
  {
    key: "cost_per_hire",
    nameAr: "تكلفة الاستقطاب للموظف الواحد",
    nameEn: "Cost Per Hire",
    category: "retention",
    categoryAr: "الاستقطاب والاحتفاظ",
    categoryEn: "Recruitment & Retention",
    unit: "ريال",
    unitAr: "ريال",
    benchmarkAr: "متوسط 4,000-8,000 ريال (حسب المستوى الوظيفي)",
    benchmarkEn: "SAR 4,000-8,000 average (by job level)",
    descriptionAr: "إجمالي تكاليف الاستقطاب مقسومة على عدد الموظفين المُعيَّنين",
    descriptionEn: "Total recruitment costs divided by number of hires",
    higherIsBetter: false,
  },
  {
    key: "time_to_fill",
    nameAr: "متوسط وقت شغل الوظيفة الشاغرة",
    nameEn: "Time to Fill",
    category: "retention",
    categoryAr: "الاستقطاب والاحتفاظ",
    categoryEn: "Recruitment & Retention",
    unit: "يوم",
    unitAr: "يوم",
    benchmarkAr: "30-45 يوماً (معيار دولي)",
    benchmarkEn: "30-45 days (global benchmark)",
    descriptionAr: "متوسط عدد الأيام من فتح الوظيفة حتى شغلها",
    descriptionEn: "Average days from job opening to filling the position",
    higherIsBetter: false,
  },
  {
    key: "probation_success_rate",
    nameAr: "معدل نجاح فترة التجربة",
    nameEn: "Probation Success Rate",
    category: "retention",
    categoryAr: "الاستقطاب والاحتفاظ",
    categoryEn: "Recruitment & Retention",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "85% وأعلى",
    benchmarkEn: "85% and above",
    descriptionAr: "نسبة الموظفين الذين اجتازوا فترة التجربة بنجاح",
    descriptionEn: "Percentage of employees who successfully completed probation",
    higherIsBetter: true,
  },
  {
    key: "retention_rate",
    nameAr: "معدل الاحتفاظ بالموظفين",
    nameEn: "Employee Retention Rate",
    category: "retention",
    categoryAr: "الاستقطاب والاحتفاظ",
    categoryEn: "Recruitment & Retention",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "85% وأعلى سنوياً",
    benchmarkEn: "85% and above annually",
    descriptionAr: "نسبة الموظفين الذين بقوا في المنظمة خلال الفترة",
    descriptionEn: "Percentage of employees retained during the period",
    higherIsBetter: true,
  },

  // ── التطوير والتدريب ──────────────────────────────────────────────────────────
  {
    key: "training_hours_per_employee",
    nameAr: "متوسط ساعات التدريب للموظف",
    nameEn: "Training Hours Per Employee",
    category: "training",
    categoryAr: "التطوير والتدريب",
    categoryEn: "Development & Training",
    unit: "ساعة",
    unitAr: "ساعة",
    benchmarkAr: "40 ساعة سنوياً (معيار دولي SHRM)",
    benchmarkEn: "40 hours annually (SHRM benchmark)",
    descriptionAr: "إجمالي ساعات التدريب مقسومة على عدد الموظفين",
    descriptionEn: "Total training hours divided by number of employees",
    higherIsBetter: true,
  },
  {
    key: "training_completion_rate",
    nameAr: "نسبة إكمال خطة التطوير",
    nameEn: "Training Completion Rate",
    category: "training",
    categoryAr: "التطوير والتدريب",
    categoryEn: "Development & Training",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "80% وأعلى",
    benchmarkEn: "80% and above",
    descriptionAr: "نسبة الموظفين الذين أكملوا برامج التدريب المخططة",
    descriptionEn: "Percentage of employees who completed planned training programs",
    higherIsBetter: true,
  },
  {
    key: "training_roi",
    nameAr: "عائد الاستثمار في التدريب (ROI)",
    nameEn: "Training ROI",
    category: "training",
    categoryAr: "التطوير والتدريب",
    categoryEn: "Development & Training",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "100% وأعلى (كل ريال يعود بريالين)",
    benchmarkEn: "100% and above",
    descriptionAr: "العائد المالي من الاستثمار في التدريب والتطوير",
    descriptionEn: "Financial return on training and development investment",
    higherIsBetter: true,
  },
  {
    key: "internal_promotion_rate",
    nameAr: "معدل الترقي الداخلي",
    nameEn: "Internal Promotion Rate",
    category: "training",
    categoryAr: "التطوير والتدريب",
    categoryEn: "Development & Training",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "30% وأعلى من الوظائف الشاغرة",
    benchmarkEn: "30% and above of vacancies filled internally",
    descriptionAr: "نسبة الوظائف التي شُغلت بترقي داخلي",
    descriptionEn: "Percentage of positions filled through internal promotion",
    higherIsBetter: true,
  },

  // ── الإنتاجية والأداء ──────────────────────────────────────────────────────────
  {
    key: "revenue_per_employee",
    nameAr: "الإيراد لكل موظف",
    nameEn: "Revenue Per Employee",
    category: "productivity",
    categoryAr: "الإنتاجية والأداء",
    categoryEn: "Productivity & Performance",
    unit: "ريال",
    unitAr: "ريال",
    benchmarkAr: "يختلف حسب القطاع",
    benchmarkEn: "Varies by industry",
    descriptionAr: "إجمالي الإيرادات مقسوماً على عدد الموظفين",
    descriptionEn: "Total revenue divided by number of employees",
    higherIsBetter: true,
  },
  {
    key: "performance_goal_achievement",
    nameAr: "نسبة إنجاز أهداف الأداء",
    nameEn: "Performance Goal Achievement",
    category: "productivity",
    categoryAr: "الإنتاجية والأداء",
    categoryEn: "Productivity & Performance",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "80% وأعلى",
    benchmarkEn: "80% and above",
    descriptionAr: "نسبة الأهداف المحققة من إجمالي الأهداف المخططة",
    descriptionEn: "Percentage of achieved goals out of total planned goals",
    higherIsBetter: true,
  },
  {
    key: "absenteeism_rate",
    nameAr: "معدل الغياب والتأخر",
    nameEn: "Absenteeism Rate",
    category: "productivity",
    categoryAr: "الإنتاجية والأداء",
    categoryEn: "Productivity & Performance",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "أقل من 3% (معيار دولي)",
    benchmarkEn: "Below 3% (global benchmark)",
    descriptionAr: "نسبة أيام الغياب من إجمالي أيام العمل المخططة",
    descriptionEn: "Percentage of absent days out of total planned working days",
    higherIsBetter: false,
  },
  {
    key: "employee_satisfaction",
    nameAr: "مؤشر رضا الموظفين (eNPS)",
    nameEn: "Employee Net Promoter Score (eNPS)",
    category: "productivity",
    categoryAr: "الإنتاجية والأداء",
    categoryEn: "Productivity & Performance",
    unit: "نقطة",
    unitAr: "نقطة",
    benchmarkAr: "أعلى من 20 نقطة (جيد) / 50+ ممتاز",
    benchmarkEn: "Above 20 (good) / 50+ excellent",
    descriptionAr: "مؤشر صافي ترويج الموظفين — مدى توصيتهم بالمنظمة كجهة عمل",
    descriptionEn: "Employee Net Promoter Score — likelihood to recommend as employer",
    higherIsBetter: true,
  },

  // ── التكاليف والكفاءة ──────────────────────────────────────────────────────────
  {
    key: "hr_cost_ratio",
    nameAr: "تكاليف الموارد البشرية كنسبة من الإيراد",
    nameEn: "HR Cost to Revenue Ratio",
    category: "cost",
    categoryAr: "التكاليف والكفاءة",
    categoryEn: "Cost & Efficiency",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "20-35% حسب القطاع",
    benchmarkEn: "20-35% depending on industry",
    descriptionAr: "إجمالي تكاليف الموارد البشرية كنسبة من الإيراد الإجمالي",
    descriptionEn: "Total HR costs as a percentage of total revenue",
    higherIsBetter: false,
  },
  {
    key: "cost_per_employee",
    nameAr: "تكلفة الموظف الواحد سنوياً",
    nameEn: "Annual Cost Per Employee",
    category: "cost",
    categoryAr: "التكاليف والكفاءة",
    categoryEn: "Cost & Efficiency",
    unit: "ريال",
    unitAr: "ريال",
    benchmarkAr: "يختلف حسب المستوى الوظيفي والقطاع",
    benchmarkEn: "Varies by job level and industry",
    descriptionAr: "إجمالي تكاليف الموظف (راتب + مزايا + تكاليف غير مباشرة)",
    descriptionEn: "Total employee cost (salary + benefits + indirect costs)",
    higherIsBetter: false,
  },
  {
    key: "saudization_cost_ratio",
    nameAr: "نسبة تكاليف التوطين",
    nameEn: "Saudization Cost Ratio",
    category: "cost",
    categoryAr: "التكاليف والكفاءة",
    categoryEn: "Cost & Efficiency",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "يختلف حسب القطاع والحجم",
    benchmarkEn: "Varies by sector and size",
    descriptionAr: "نسبة تكاليف برامج التوطين من إجمالي تكاليف الموارد البشرية",
    descriptionEn: "Saudization program costs as a percentage of total HR costs",
    higherIsBetter: false,
  },
  {
    key: "hr_to_employee_ratio",
    nameAr: "نسبة موظفي الموارد البشرية للموظفين",
    nameEn: "HR to Employee Ratio",
    category: "cost",
    categoryAr: "التكاليف والكفاءة",
    categoryEn: "Cost & Efficiency",
    unit: "لكل 100",
    unitAr: "لكل 100 موظف",
    benchmarkAr: "1-2 موظف موارد بشرية لكل 100 موظف",
    benchmarkEn: "1-2 HR staff per 100 employees",
    descriptionAr: "عدد موظفي الموارد البشرية مقابل كل 100 موظف",
    descriptionEn: "Number of HR staff per 100 employees",
    higherIsBetter: false,
  },

  // ── الحوكمة المؤسسية ──────────────────────────────────────────────────────────
  {
    key: "policy_compliance_rate",
    nameAr: "نسبة الالتزام بالسياسات والإجراءات",
    nameEn: "Policy Compliance Rate",
    category: "governance",
    categoryAr: "الحوكمة المؤسسية",
    categoryEn: "Corporate Governance",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "95% وأعلى",
    benchmarkEn: "95% and above",
    descriptionAr: "نسبة الالتزام بسياسات وإجراءات الموارد البشرية المعتمدة",
    descriptionEn: "Compliance rate with approved HR policies and procedures",
    higherIsBetter: true,
  },
  {
    key: "grievance_resolution_rate",
    nameAr: "معدل حل الشكاوى والتظلمات",
    nameEn: "Grievance Resolution Rate",
    category: "governance",
    categoryAr: "الحوكمة المؤسسية",
    categoryEn: "Corporate Governance",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "90% وأعلى خلال 30 يوماً",
    benchmarkEn: "90% and above within 30 days",
    descriptionAr: "نسبة الشكاوى والتظلمات التي تم حلها من إجمالي المستلمة",
    descriptionEn: "Percentage of grievances resolved out of total received",
    higherIsBetter: true,
  },
  {
    key: "succession_plan_coverage",
    nameAr: "تغطية خطط الخلافة الوظيفية",
    nameEn: "Succession Plan Coverage",
    category: "governance",
    categoryAr: "الحوكمة المؤسسية",
    categoryEn: "Corporate Governance",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "80% من المناصب الحرجة لديها خطة خلافة",
    benchmarkEn: "80% of critical positions have succession plans",
    descriptionAr: "نسبة المناصب الحرجة التي لديها خطط خلافة معتمدة",
    descriptionEn: "Percentage of critical positions with approved succession plans",
    higherIsBetter: true,
  },
  {
    key: "hr_audit_score",
    nameAr: "نتيجة تدقيق الموارد البشرية",
    nameEn: "HR Audit Score",
    category: "governance",
    categoryAr: "الحوكمة المؤسسية",
    categoryEn: "Corporate Governance",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "85% وأعلى",
    benchmarkEn: "85% and above",
    descriptionAr: "النتيجة الإجمالية لتدقيق ممارسات الموارد البشرية",
    descriptionEn: "Overall score from HR practices audit",
    higherIsBetter: true,
  },
  {
    key: "labor_law_compliance",
    nameAr: "نسبة الامتثال لنظام العمل",
    nameEn: "Labor Law Compliance Rate",
    category: "governance",
    categoryAr: "الحوكمة المؤسسية",
    categoryEn: "Corporate Governance",
    unit: "%",
    unitAr: "%",
    benchmarkAr: "100% (الامتثال الكامل مطلوب)",
    benchmarkEn: "100% (full compliance required)",
    descriptionAr: "نسبة الامتثال لمتطلبات نظام العمل السعودي ولوائحه",
    descriptionEn: "Compliance rate with Saudi Labor Law requirements and regulations",
    higherIsBetter: true,
  },
];

/**
 * Calculate traffic light status based on current vs target
 */


async function tr(db: MySql2Database<any>, entityType: string, entityId: number, lang: string, field: string, value: string) {
  await db.insert(translations).values({ entityType, entityId, lang, field, value });
}

export async function seedHcIndicators(db: MySql2Database<any>) {
  console.log("📊 Seeding HC KPI indicators...");

  // idempotent: clear owned rows before re-inserting
  await db.delete(translations).where(
    inArray(translations.entityType, ["hc_kpi_category", "hc_builtin_indicator"]),
  );
  await db.delete(hcBuiltinIndicators);
  await db.delete(hcKpiCategories);

  const catIdMap: Record<string, number> = {};
  for (let i = 0; i < HC_CATEGORIES.length; i++) {
    const cat = HC_CATEGORIES[i];
    const [result] = await db.insert(hcKpiCategories).values({
      code: cat.key, color: cat.color, icon: "📊", sortOrder: i,
    });
    const id = Number(result.insertId);
    catIdMap[cat.key] = id;
    await tr(db, "hc_kpi_category", id, "ar", "name", cat.ar);
    await tr(db, "hc_kpi_category", id, "en", "name", cat.en);
  }

  for (let i = 0; i < BUILTIN_INDICATORS.length; i++) {
    const ind = BUILTIN_INDICATORS[i];
    const [result] = await db.insert(hcBuiltinIndicators).values({
      key: ind.key,
      categoryId: catIdMap[ind.category] ?? 0,
      unit: ind.unit,
      higherIsBetter: ind.higherIsBetter ? 1 : 0,
      sortOrder: i,
    });
    const id = Number(result.insertId);
    await tr(db, "hc_builtin_indicator", id, "ar", "name", ind.nameAr);
    await tr(db, "hc_builtin_indicator", id, "en", "name", ind.nameEn);
    await tr(db, "hc_builtin_indicator", id, "ar", "benchmark", ind.benchmarkAr);
    await tr(db, "hc_builtin_indicator", id, "en", "benchmark", ind.benchmarkEn);
    await tr(db, "hc_builtin_indicator", id, "ar", "description", ind.descriptionAr);
    await tr(db, "hc_builtin_indicator", id, "en", "description", ind.descriptionEn);
  }

  console.log(`   ✓ HC indicators seeded (${HC_CATEGORIES.length} categories, ${BUILTIN_INDICATORS.length} indicators)`);
}
