// ملف البيانات الوزارية الشامل - مستخرج من القرارات الوزارية
// آخر تحديث: 2026

export interface Profession {
  name: string;
  code: string;
  minWage?: number;
}

export interface ImplementationPhase {
  phase: number;
  description: string;
  percentage?: number;
  date?: string;
}

export interface MinisterialSector {
  id: string;
  name: string;
  decisionNumber: string;
  decisionDate: string;
  saudizationPercentage: number;
  minWage: number;
  minEmployees: number;
  professions: Profession[];
  excludedProfessions: string;
  implementationPhases: ImplementationPhase[];
  notes?: string;
}

export const ministerialSectors: MinisterialSector[] = [
  {
    id: "project-management",
    name: "مهن إدارة المشاريع",
    decisionNumber: "141749",
    decisionDate: "2023/04/02",
    saudizationPercentage: 40,
    minWage: 6000,
    minEmployees: 3,
    professions: [
      { name: "مدير إدارة مشاريع", code: "121314" },
      { name: "أخصائي إدارة مشاريع", code: "242108" },
      { name: "مدير مشاريع", code: "2133241" },
      { name: "أخصائي مكتب إدارة المشاريع", code: "2133231" },
      { name: "مدير مشروع اتصالات", code: "1216031" },
      { name: "مدير مشروع لخدمات الأعمال", code: "1217011" },
      { name: "مدير مشروع نقل", code: "1216011" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "توطين نسبة 35%", percentage: 35, date: "2023/12/24" },
      { phase: 2, description: "توطين نسبة 40%", percentage: 40, date: "2024/12/12" },
    ],
  },
  {
    id: "ict",
    name: "مهن الاتصالات وتقنية المعلومات",
    decisionNumber: "28889",
    decisionDate: "2019/08/06",
    saudizationPercentage: 25,
    minWage: 5000,
    minEmployees: 5,
    professions: [
      { name: "مهندس حاسب آلي", code: "2214061" },
      { name: "مهندس اتصالات", code: "2214041" },
      { name: "مهندس شبكات", code: "2133161" },
      { name: "مهندس شبكات الأقمار الصناعية", code: "2214101" },
      { name: "مهندس إذاعة وتلفزة", code: "2214021" },
      { name: "أخصائي تطوير البرمجيات", code: "2133251" },
      { name: "أخصائي هندسة البرمجيات", code: "2133311" },
      { name: "أخصائي تحليل الأعمال", code: "2133111" },
      { name: "مبرمج حاسب آلي", code: "2133031" },
      { name: "محلل نظم عام", code: "2133011" },
      { name: "أخصائي مكتب الدعم الفني", code: "2133191" },
      { name: "أخصائي دعم فني", code: "2133211" },
      { name: "فني حاسب آلي", code: "3214072" },
      { name: "فني مكتب الدعم الفني", code: "3132042" },
      { name: "مشغل حاسب آلي", code: "4234013" },
      { name: "إداري إنترنت", code: "2133281" },
      { name: "فني إلكتروني اتصالات", code: "3214042" },
      { name: "فني شبكات حاسب", code: "3132032" },
      { name: "إداري شبكات", code: "2133171" },
      { name: "فني هندسة اتصالات", code: "3214092" },
      { name: "فني تلفونات", code: "3214112" },
      { name: "فني هاتف سيار", code: "3214102" },
    ],
    excludedProfessions: "المنشآت الصغيرة العاملة في نشاط الاتصالات وتقنية المعلومات",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 25, date: "2021/10/23" },
    ],
  },
  {
    id: "marketing",
    name: "مهن التسويق",
    decisionNumber: "101319",
    decisionDate: "2026/01/19",
    saudizationPercentage: 60,
    minWage: 5500,
    minEmployees: 3,
    professions: [
      { name: "مدير تسويق", code: "122103" },
      { name: "وكيل دعاية وإعلان", code: "333901" },
      { name: "مدير دعاية وإعلان", code: "122201" },
      { name: "مصمم جرافيك", code: "216601" },
      { name: "أخصائي علاقات عامة", code: "243202" },
      { name: "أخصائي دعاية وإعلان", code: "243101" },
      { name: "أخصائي تسويق", code: "243110" },
      { name: "مدير علاقات عامة", code: "122203" },
      { name: "مصور فوتوغرافي", code: "343101" },
      { name: "مصمم إعلان", code: "216604" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 60, date: "2026/01/19" },
    ],
  },
  {
    id: "sales",
    name: "مهن المبيعات",
    decisionNumber: "101278",
    decisionDate: "2026/01/19",
    saudizationPercentage: 60,
    minWage: 4000,
    minEmployees: 3,
    professions: [
      { name: "مدير مبيعات", code: "122104" },
      { name: "مدير مبيعات تجزئة", code: "142001" },
      { name: "مدير مبيعات جملة", code: "142003" },
      { name: "مندوب مبيعات", code: "332201" },
      { name: "أخصائي مبيعات أجهزة تقنية المعلومات والاتصالات", code: "243401" },
      { name: "أخصائي مبيعات", code: "243190" },
      { name: "أخصائي تجاري", code: "243160" },
      { name: "وسيط سلع", code: "332402" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 60, date: "2026/01/19" },
    ],
  },
  {
    id: "procurement",
    name: "مهن المشتريات",
    decisionNumber: "77050",
    decisionDate: "2025/11/30",
    saudizationPercentage: 70,
    minWage: 4000,
    minEmployees: 3,
    professions: [
      { name: "أخصائي مناقصات", code: "243104" },
      { name: "أخصائي مشتريات", code: "243102" },
      { name: "أخصائي تجارة إلكترونية", code: "243107" },
      { name: "أخصائي أبحاث أسواق", code: "243108" },
      { name: "أخصائي مستودعات", code: "241110" },
      { name: "مدير مشتريات", code: "132417" },
      { name: "مندوب مشتريات", code: "332302" },
      { name: "مدير عقود", code: "122105" },
      { name: "مدير خدمات لوجستية", code: "132415" },
      { name: "مدير مستودع", code: "132418" },
      { name: "أمين مستودع", code: "313907" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 70, date: "2025/11/30" },
    ],
  },
  {
    id: "customer-service",
    name: "مهن خدمة العملاء",
    decisionNumber: "208892",
    decisionDate: "2022/06/22",
    saudizationPercentage: 100,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "كاتب استعلامات", code: "422101" },
      { name: "كاتب استعلامات سياحية", code: "422102" },
      { name: "كاتب تذاكر سفر", code: "422103" },
      { name: "كاتب مركز اتصالات", code: "422201" },
      { name: "كاتب استعلامات مركز خدمة عملاء", code: "422202" },
      { name: "مراقب حركة", code: "422301" },
      { name: "مشغل مقسم هاتف", code: "422302" },
      { name: "كاتب اتصال", code: "422303" },
      { name: "كاتب بيانات عملاء", code: "422902" },
    ],
    excludedProfessions: "مهن خدمة العملاء المستثناة بالتنسيق مع الجهات الإشرافية",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 100, date: "2022/06/22" },
    ],
  },
  {
    id: "remote-customer-service",
    name: "مهن خدمة العملاء عن بُعد",
    decisionNumber: "112203",
    decisionDate: "2021/05/30",
    saudizationPercentage: 100,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "جميع مهن خدمة العملاء عن بعد (رمز 42)", code: "42" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 100, date: "2021/05/30" },
    ],
    notes: "يشمل جميع المهن المصنفة ضمن مهن خدمة العملاء التي تقدم عن بعد",
  },
  {
    id: "sports-centers",
    name: "مهن المراكز الرياضية",
    decisionNumber: "72002",
    decisionDate: "2025/11/18",
    saudizationPercentage: 15,
    minWage: 4000,
    minEmployees: 4,
    professions: [
      { name: "مدرب رياضي", code: "342201" },
      { name: "مدرب لياقة بدنية", code: "342301" },
      { name: "مدرب كرة قدم معتمد", code: "342203" },
      { name: "مدرب رياضي خاص", code: "342302" },
      { name: "مدرب رياضة مائية معتمد", code: "342211" },
      { name: "مشرف رياضي", code: "342221" },
      { name: "مدرب قوة وألعاب معتمد", code: "342219" },
      { name: "مدرب فروسية معتمد", code: "342217" },
      { name: "مدرب رياضة جليدية معتمد", code: "342213" },
      { name: "مدرب رياضة بالكرة معتمد", code: "342205" },
      { name: "مدرب رياضة دفاع عن النفس معتمد", code: "342207" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 15, date: "2025/11/18" },
    ],
  },
  {
    id: "tourism",
    name: "القطاع السياحي",
    decisionNumber: "137440",
    decisionDate: "2025/01/22",
    saudizationPercentage: 100,
    minWage: 5500,
    minEmployees: 1,
    professions: [
      { name: "موظف استقبال فندق", code: "422401" },
      { name: "موظف استقبال", code: "422601" },
      { name: "كاتب استعلامات", code: "422501" },
      { name: "مرشد سياحي", code: "511301" },
      { name: "أخصائي رقابة فندقية", code: "263212" },
      { name: "مدير فرع", code: "112008" },
      { name: "مراقب فنادق", code: "335904" },
      { name: "مدير رقابة فنادق", code: "141103" },
      { name: "أخصائي إرشاد سياحي", code: "263208" },
      { name: "أخصائي علاقات عامة", code: "243202" },
      { name: "مضيف نادي صحي", code: "514204" },
      { name: "أخصائي سياحة", code: "263211" },
      { name: "منظم سياحي", code: "333905" },
      { name: "بائع تذاكر", code: "523002" },
      { name: "مشرف تدبير وتنظيف", code: "515101" },
      { name: "مضيف مطعم", code: "513101" },
      { name: "منسق فعاليات", code: "333202" },
      { name: "مندوب مبيعات", code: "332201" },
      { name: "وكيل سياحي", code: "333904" },
      { name: "طاهي", code: "512001", minWage: 4000 },
      { name: "مدير عمليات فندقية", code: "141102" },
      { name: "مدير مبيعات", code: "122104" },
      { name: "مدير مطعم", code: "141203" },
      { name: "مدير فندق", code: "141101" },
      { name: "مدير تسويق", code: "122103" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "100% على المهن الاستقبالية والإرشادية", percentage: 100, date: "2026/01/22" },
      { phase: 2, description: "30% على مهنة طاهي", percentage: 30, date: "2027/01/01" },
      { phase: 3, description: "50% على مجموعة المدراء", percentage: 50, date: "2028/01/01" },
    ],
  },
  {
    id: "clinical-nutrition",
    name: "مهن التغذية العلاجية",
    decisionNumber: "51277",
    decisionDate: "2025/04/12",
    saudizationPercentage: 80,
    minWage: 5000,
    minEmployees: 1,
    professions: [
      { name: "أخصائي تغذية", code: "226501" },
      { name: "أخصائي تغذية سريرية", code: "226502" },
      { name: "أخصائي تغذية عام", code: "2316011" },
      { name: "أخصائي تغذية مرضى", code: "2316021" },
      { name: "فني تغذية", code: "325908" },
      { name: "فني مختبر تغذية", code: "3111042" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "المدن الرئيسية والمنشآت الكبيرة", percentage: 80, date: "2025/10/12" },
      { phase: 2, description: "جميع المنشآت في جميع المناطق", percentage: 80, date: "2026/04/14" },
    ],
  },
  {
    id: "radiology",
    name: "مهن الأشعة",
    decisionNumber: "51273",
    decisionDate: "2025/04/12",
    saudizationPercentage: 65,
    minWage: 7000,
    minEmployees: 1,
    professions: [
      { name: "فني أشعة", code: "321102" },
      { name: "أخصائي تقنية إشعاعية", code: "224002" },
      { name: "فني تصوير إشعاعي", code: "3315012" },
      { name: "فني تصوير موجي", code: "3315022" },
      { name: "فني قسطرة قلب", code: "3311152" },
      { name: "أخصائي تصوير طبي", code: "2315031" },
      { name: "أخصائي معالجة الأشعة", code: "2315051" },
      { name: "مدرب أخصائي أشعة", code: "2315271" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "المدن الرئيسية والمنشآت الكبيرة", percentage: 65, date: "2025/10/12" },
      { phase: 2, description: "جميع المنشآت في كل المناطق", percentage: 65, date: "2026/04/14" },
    ],
  },
  {
    id: "medical-labs",
    name: "مهن المختبرات الطبية",
    decisionNumber: "51267",
    decisionDate: "2025/04/12",
    saudizationPercentage: 70,
    minWage: 5000,
    minEmployees: 1,
    professions: [
      { name: "فني مختبر طبي", code: "321201" },
      { name: "أخصائي مختبرات طبية", code: "213115" },
      { name: "مدير مختبر تحاليل طبية", code: "134207" },
      { name: "أخصائي تحاليل طبية", code: "2315011" },
      { name: "أخصائي مختبر أنسجة حية", code: "2315021" },
      { name: "استشاري تحاليل طبية", code: "2315141" },
      { name: "فني مختبر عام", code: "3316012" },
      { name: "فني مختبر دم ومصرف", code: "3316022" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "المدن الرئيسية والمنشآت الكبيرة", percentage: 70, date: "2025/10/17" },
      { phase: 2, description: "جميع المنشآت في كل المناطق", percentage: 70, date: "2026/04/17" },
    ],
  },
  {
    id: "dentistry",
    name: "مهن طب الأسنان",
    decisionNumber: "103107",
    decisionDate: "2025/01/26",
    saudizationPercentage: 55,
    minWage: 9000,
    minEmployees: 3,
    professions: [
      { name: "طبيب أسنان عام", code: "226101" },
      { name: "طبيب فم ووجه وفكين", code: "226102" },
      { name: "جراح فم ووجه وفكين", code: "226103" },
      { name: "طبيب تقويم أسنان", code: "226108" },
      { name: "طبيب علاج لبي", code: "226104" },
      { name: "طبيب أسنان أطفال", code: "226106" },
      { name: "طبيب صحة عامة أسنان", code: "226105" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "توطين 45%", percentage: 45, date: "2025/07/27" },
      { phase: 2, description: "توطين 55%", percentage: 55, date: "2026/01/27" },
    ],
  },
  {
    id: "pharmacy",
    name: "مهن الصيدلة",
    decisionNumber: "103111",
    decisionDate: "2025/01/26",
    saudizationPercentage: 65,
    minWage: 7000,
    minEmployees: 5,
    professions: [
      { name: "صيدلي", code: "226201" },
      { name: "صيدلي رعاية صيدلانية", code: "226202" },
      { name: "أخصائي علوم صيدلانية", code: "211303" },
      { name: "أخصائي علوم أدوية", code: "213109" },
      { name: "أخصائي إدارة صيدلانية", code: "242112" },
      { name: "أخصائي مبيعات منتجات صيدلانية", code: "243302" },
      { name: "مدير صيدلة", code: "134211" },
      { name: "مدير رقابة صيدلية", code: "134212" },
      { name: "أخصائي أدوية عام", code: "2321011" },
      { name: "أخصائي سموم", code: "2321061" },
      { name: "استشاري أدوية", code: "2321071" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 65, date: "2025/01/26" },
    ],
  },
  {
    id: "engineering",
    name: "المهن الهندسية",
    decisionNumber: "93483",
    decisionDate: "2025/12/31",
    saudizationPercentage: 30,
    minWage: 8000,
    minEmployees: 5,
    professions: [
      { name: "مهندس مدني", code: "214201" },
      { name: "مهندس معماري", code: "216101" },
      { name: "مهندس كهربائي", code: "215101" },
      { name: "مهندس ميكانيكي", code: "214401" },
      { name: "مهندس صناعي", code: "214101" },
      { name: "مهندس كيميائي", code: "214501" },
      { name: "مهندس بيئي", code: "214301" },
      { name: "مهندس إلكترونيات", code: "215201" },
      { name: "مهندس طرق", code: "214206" },
      { name: "مهندس جسور", code: "214207" },
      { name: "مهندس إنشائي", code: "214205" },
      { name: "مهندس نفط وغاز", code: "214603" },
      { name: "مهندس تعدين", code: "214601" },
      { name: "مهندس طيران", code: "214404" },
      { name: "مهندس أنظمة", code: "215105" },
      { name: "مهندس توليد طاقة", code: "215106" },
      { name: "مهندس معماري داخلي", code: "216102" },
      { name: "مهندس تدفئة وتهوية وتكييف", code: "214406" },
      { name: "مهندس مواد", code: "214904" },
      { name: "مهندس بحري", code: "214405" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 30, date: "2025/12/31" },
    ],
  },
  {
    id: "technical-engineering",
    name: "المهن الفنية الهندسية",
    decisionNumber: "103105",
    decisionDate: "2025/01/26",
    saudizationPercentage: 30,
    minWage: 5000,
    minEmployees: 5,
    professions: [
      { name: "فني مدني", code: "311201" },
      { name: "فني كهربائي", code: "311301" },
      { name: "فني ميكانيكي", code: "311501" },
      { name: "فني إلكتروني", code: "311403" },
      { name: "فني كيميائي", code: "311601" },
      { name: "فني معماري", code: "311906" },
      { name: "رسام هندسي", code: "311801" },
      { name: "مساح", code: "216501" },
      { name: "فني مساحة", code: "311211" },
      { name: "فني صيانة إنشائية", code: "311205" },
      { name: "فني صيانة مباني", code: "311207" },
      { name: "فني تكييف وتهوية وتدفئة", code: "311502" },
      { name: "فني محركات", code: "311506" },
      { name: "فني مركبات", code: "311507" },
      { name: "مشرف إنشاء مباني", code: "312301" },
      { name: "مشرف إنشاء طرق", code: "312302" },
      { name: "مشرف صيانة", code: "312203" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "فترة سماح 6 أشهر من 2025/01/26", percentage: 30, date: "2025/07/27" },
    ],
  },
  {
    id: "legal",
    name: "المهن القانونية",
    decisionNumber: "212607",
    decisionDate: "2021/07/04",
    saudizationPercentage: 70,
    minWage: 5500,
    minEmployees: 1,
    professions: [
      { name: "مستشار قانوني نظم عامة", code: "2432011" },
      { name: "مستشار قانوني نظم خاصة", code: "2432021" },
      { name: "أخصائي عقود", code: "241318" },
      { name: "كاتب شؤون قانونية", code: "4112053" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "توطين 50%", percentage: 50, date: "2021/07/04" },
      { phase: 2, description: "توطين 70%", percentage: 70, date: "2022/01/04" },
    ],
  },
  {
    id: "real-estate",
    name: "قطاع العقار",
    decisionNumber: "212535",
    decisionDate: "2021/07/04",
    saudizationPercentage: 70,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "وسيط عقاري", code: "5113063" },
      { name: "وسيط بيع وتأجير عقارات", code: "5121033" },
      { name: "سمسار أراضي وعقارات", code: "5113013" },
      { name: "كاتب تسجيل أراضي وعقارات", code: "4123023" },
      { name: "مسوق عقاري", code: "5113053" },
      { name: "مدير اتحاد ملاك", code: "1213012" },
      { name: "مهندس مستدام معتمد", code: "2211061" },
      { name: "مهندس مقيم معتمد", code: "2211051" },
    ],
    excludedProfessions: "أنشطة تطوير مشاريع المباني للبيع وتقسيم الأراضي وتقييم العقارات في هذه المرحلة",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة بعد فترة سماح 90 يوماً", percentage: 70, date: "2021/10/02" },
    ],
  },
  {
    id: "wellness-centers",
    name: "مراكز الاسترخاء والعناية الشخصية",
    decisionNumber: "68098",
    decisionDate: "2025/11/11",
    saudizationPercentage: 100,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "مساعد حسابات", code: "331301" },
      { name: "مدير فرع", code: "112008" },
      { name: "مندوب مبيعات", code: "332201" },
      { name: "مدير إداري", code: "121902" },
      { name: "مندوب مشتريات", code: "332302" },
      { name: "مدير تسويق", code: "122103" },
      { name: "مدير خدمة عملاء", code: "122102" },
      { name: "مدير مبيعات", code: "122104" },
      { name: "مساعد إداري", code: "412001" },
      { name: "سكرتير", code: "412002" },
      { name: "مدير متجر", code: "142002" },
      { name: "مدخل بيانات", code: "413201" },
      { name: "مدير نادي صحي", code: "143104" },
      { name: "موظف استقبال", code: "422601" },
      { name: "محاسب", code: "241101" },
      { name: "أمين صندوق", code: "432101" },
      { name: "أمين متجر", code: "522101" },
      { name: "أخصائي إداري", code: "242121" },
      { name: "مراقب متجر", code: "522201" },
      { name: "أخصائي مشتريات", code: "243102" },
      { name: "بائع", code: "522301" },
      { name: "أخصائي خدمة عملاء", code: "243105" },
      { name: "أخصائي مبيعات", code: "243109" },
      { name: "أخصائي تسويق", code: "243110" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 100, date: "2025/11/11" },
    ],
  },
  {
    id: "housing-supervisor",
    name: "مهنة مشرف سكن",
    decisionNumber: "62298",
    decisionDate: "2025/10/31",
    saudizationPercentage: 100,
    minWage: 5000,
    minEmployees: 1,
    professions: [
      { name: "مشرف سكن", code: "515102" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "يبدأ التطبيق بعد فترة سماح 3 أشهر", percentage: 100, date: "2026/02/01" },
    ],
  },
  {
    id: "optics",
    name: "قطاع البصريات",
    decisionNumber: "208837",
    decisionDate: "2022/06/22",
    saudizationPercentage: 50,
    minWage: 5500,
    minEmployees: 4,
    professions: [
      { name: "فني بصريات طبية", code: "325401" },
      { name: "فني نظارات", code: "325403" },
      { name: "فني مختبرات ضوئية وبصريات", code: "3112042" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة (فترة سماح 270 يوماً)", percentage: 50, date: "2023/03/19" },
    ],
  },
  {
    id: "cinema",
    name: "السينما",
    decisionNumber: "212560",
    decisionDate: "2021/07/04",
    saudizationPercentage: 100,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "بائع تذاكر", code: "523002" },
      { name: "بائع مأكولات ومشروبات", code: "522301" },
      { name: "مشغل جهاز عرض سينمائي", code: "352201" },
      { name: "فني عروض سينمائية", code: "352202" },
      { name: "جميع المهن الإشرافية والإدارية", code: "-" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "100% في جميع دور عرض الأفلام السينمائية", percentage: 100, date: "2021/07/04" },
    ],
  },
  {
    id: "restaurants",
    name: "المطاعم والمقاهي",
    decisionNumber: "160045",
    decisionDate: "2021/04/07",
    saudizationPercentage: 30,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "كاشير / أمين صندوق", code: "432101" },
      { name: "مضيف مطعم", code: "513101" },
      { name: "مدير مطعم", code: "141203" },
      { name: "مشرف قسم", code: "335907" },
      { name: "بائع مأكولات", code: "522301" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 30, date: "2021/04/07" },
    ],
    notes: "يستهدف المنافذ الأمامية (الكاشير والاستقبال والإشراف)",
  },
  {
    id: "malls",
    name: "المجمعات التجارية المغلقة (المولات)",
    decisionNumber: "159986",
    decisionDate: "2022/01/28",
    saudizationPercentage: 100,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "جميع المهن الإدارية والإشرافية", code: "-" },
      { name: "مهن البيع", code: "522301" },
      { name: "مهن المحاسبة", code: "241101" },
      { name: "مهن خدمة العملاء", code: "422101" },
      { name: "مهن الصيانة", code: "311201" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 100, date: "2022/01/28" },
    ],
  },
  {
    id: "supermarkets",
    name: "التموينات والأسواق المركزية",
    decisionNumber: "160008",
    decisionDate: "2021/04/07",
    saudizationPercentage: 100,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "محاسب زبائن (كاشير)", code: "432101" },
      { name: "مشرف صناديق المحاسبة", code: "335907" },
      { name: "خدمة العملاء / علاقات العملاء", code: "422101" },
      { name: "مشرف قسم", code: "335901" },
      { name: "مدير قسم", code: "132301" },
      { name: "مساعد مدير فرع", code: "112009" },
      { name: "مدير فرع", code: "112008" },
    ],
    excludedProfessions: "عامل تعبئة رفوف",
    implementationPhases: [
      { phase: 1, description: "100% لمهن الكاشير وخدمة العملاء، 50% لمشرف قسم", percentage: 100, date: "2021/04/07" },
      { phase: 2, description: "100% لمشرف قسم، 50% لمدير قسم ومدير فرع", percentage: 100, date: "2022/04/07" },
    ],
  },
  {
    id: "wholesale-retail",
    name: "البيع بالجملة والتجزئة",
    decisionNumber: "16655",
    decisionDate: "2024/08/11",
    saudizationPercentage: 70,
    minWage: 4000,
    minEmployees: 4,
    professions: [
      { name: "بائع تجزئة (عام)", code: "464961" },
      { name: "بائع ملابس", code: "464121" },
      { name: "بائع أحذية", code: "464171" },
      { name: "بائع أجهزة إلكترونية", code: "464996" },
      { name: "بائع حاسبات", code: "465101" },
      { name: "بائع أثاث منزلي", code: "464912" },
      { name: "بائع مواد بناء", code: "475281" },
      { name: "بائع سيارات", code: "451011" },
      { name: "بائع قطع غيار سيارات", code: "451021" },
      { name: "بائع أغذية ومشروبات", code: "461015" },
      { name: "بائع خضروات وفواكه", code: "463011" },
      { name: "بائع لحوم", code: "463041" },
      { name: "بائع حلويات ومخبوزات", code: "472161" },
      { name: "بائع أدوات ومستلزمات طبية", code: "464956" },
      { name: "بائع هدايا وتحف", code: "469040" },
      { name: "بائع كتب وأدوات مكتبية", code: "464962" },
      { name: "بائع ساعات", code: "464981" },
      { name: "بائع نظارات", code: "464971" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 70, date: "2024/08/11" },
    ],
  },
  {
    id: "entertainment",
    name: "مدن الملاهي والمراكز الترفيهية",
    decisionNumber: "165575",
    decisionDate: "2022/04/01",
    saudizationPercentage: 70,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "جميع المهن الإدارية والإشرافية", code: "-" },
      { name: "بائع تذاكر", code: "523002" },
      { name: "مشغل ألعاب", code: "342901" },
      { name: "مدير مركز ترفيهي", code: "143901" },
    ],
    excludedProfessions: "نادلة، عامل نظافة، مشغلي الألعاب النوعية التي تتطلب شهادات تخصصية",
    implementationPhases: [
      { phase: 1, description: "70% للمراكز الترفيهية المستقلة، 100% داخل المجمعات التجارية", percentage: 70, date: "2022/04/01" },
    ],
  },
  {
    id: "customs-clearance",
    name: "نشاط ومهن التخليص الجمركي",
    decisionNumber: "212497",
    decisionDate: "2021/07/04",
    saudizationPercentage: 70,
    minWage: 5000,
    minEmployees: 1,
    professions: [
      { name: "كاتب تخليص جمركي", code: "4211103" },
      { name: "مبند جمركي", code: "5123033" },
      { name: "مترجم", code: "2511041" },
      { name: "مدير عام", code: "1111031" },
      { name: "مسؤول علاقات حكومية", code: "6223025" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 70, date: "2021/07/04" },
    ],
  },
  {
    id: "freight",
    name: "خدمات الشحن ووسطاء الشحن",
    decisionNumber: "دليل إجرائي",
    decisionDate: "2024",
    saudizationPercentage: 70,
    minWage: 5000,
    minEmployees: 3,
    professions: [
      { name: "وسيط شحن", code: "333901" },
      { name: "مدير عمليات شحن", code: "132415" },
      { name: "أخصائي لوجستيات", code: "241110" },
      { name: "مسؤول علاقات حكومية", code: "6223025" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 70 },
    ],
  },
  {
    id: "accounting",
    name: "المهن المحاسبية",
    decisionNumber: "دليل إجرائي",
    decisionDate: "2023",
    saudizationPercentage: 70,
    minWage: 5500,
    minEmployees: 3,
    professions: [
      { name: "محاسب قانوني", code: "241101" },
      { name: "محاسب عام", code: "241102" },
      { name: "مراجع حسابات", code: "241103" },
      { name: "أخصائي ضرائب", code: "241104" },
      { name: "مدير مالي", code: "121101" },
      { name: "أخصائي مالي", code: "241105" },
      { name: "محلل مالي", code: "241106" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 70 },
    ],
  },
  {
    id: "private-education",
    name: "قطاع التعليم العام الأهلي",
    decisionNumber: "دليل إجرائي",
    decisionDate: "2023",
    saudizationPercentage: 75,
    minWage: 5000,
    minEmployees: 1,
    professions: [
      { name: "معلم ابتدائي", code: "233101" },
      { name: "معلم متوسط", code: "233102" },
      { name: "معلم ثانوي", code: "233103" },
      { name: "مدير مدرسة", code: "134901" },
      { name: "مشرف تربوي", code: "235101" },
      { name: "أخصائي اجتماعي مدرسي", code: "263601" },
      { name: "مرشد طلابي", code: "263602" },
    ],
    excludedProfessions: "معلمو اللغات الأجنبية في حال عدم توفر كفاءات سعودية",
    implementationPhases: [
      { phase: 1, description: "مرحلة واحدة", percentage: 75 },
    ],
  },
  {
    id: "beauty-tailoring",
    name: "منافذ التزيين والخياطة النسائية",
    decisionNumber: "دليل إجرائي",
    decisionDate: "2021",
    saudizationPercentage: 100,
    minWage: 4000,
    minEmployees: 1,
    professions: [
      { name: "حلاقة نسائية", code: "514101" },
      { name: "خبيرة تجميل", code: "514102" },
      { name: "خياطة نسائية", code: "753101" },
      { name: "مصممة أزياء", code: "216301" },
      { name: "مشغلة صالون", code: "143901" },
    ],
    excludedProfessions: "لا يوجد",
    implementationPhases: [
      { phase: 1, description: "قصر العمل على السعوديات 100%", percentage: 100 },
    ],
  },
];

export function findSector(query: string): MinisterialSector | undefined {
  const q = query.toLowerCase();
  return ministerialSectors.find(
    (s) => s.id === q || s.name.includes(query) || s.id.includes(q)
  );
}

export function findProfession(professionName: string): { sector: MinisterialSector; profession: Profession }[] {
  const results: { sector: MinisterialSector; profession: Profession }[] = [];
  for (const sector of ministerialSectors) {
    for (const prof of sector.professions) {
      if (prof.name.includes(professionName) || prof.code === professionName) {
        results.push({ sector, profession: prof });
      }
    }
  }
  return results;
}

export function getSectorsForCalculator() {
  return ministerialSectors.map((s) => ({
    id: s.id,
    name: s.name,
    percentage: s.saudizationPercentage,
    minWage: s.minWage,
    minEmployees: s.minEmployees,
    professionCount: s.professions.length,
  }));
}
